### ISSUE TITLE
Add to mobile clients Ethereum multiSig wallet

### ISSUE THREAD

**Issue by vadimicus** [Multy-io/Multy-Android#29]
MultiSig should be based on the gnosis smart contract.
User in the app should have possibility to create new multiSig wallet and invite other users there.
In case of the transaction propose, all owners of the wallet should have logic to confirm or reject the transaction.

App should be available on Google Play and Appstore.

**Comment by xhipster** [comment]
Ability to import account using raw private key or keystore is also very needed

**Comment by vadimicus** [comment]
Done
