### ISSUE TITLE
 use of undeclared identifier 'account_change_private_key'

### ISSUE THREAD

**Issue by muzammilhussnain14** [Multy-io/Multy-Android#70]
**Getting following error**

> Build command failed.
Error while executing process C:\Users\Microsoft\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build F:\GitHub\Multy-Android\app\.externalNativeBuild\cmake\stageDebug\x86 --target multy_core_jni}
[1/3] cmd.exe /C "cd /D F:\GitHub\Multy-Android\app\.externalNativeBuild\cmake\stageDebug\x86\multy_core && C:\Users\Microsoft\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe -DIN_FILE=F:/GitHub/Multy-Core/multy_core/src/version.h.template -DOUT_FILE=F:/GitHub/Multy-Android/app/.externalNativeBuild/cmake/stageDebug/x86/multy_core/include/generated/version.h -DGIT_DIR=F:/GitHub/Multy-Core/multy_core -P F:/GitHub/Multy-Core/multy_core/version_from_git.cmake"
fatal: no tag exactly matches 'ef13ee5f616ce84f2a6ad8ec023ea4d6d31ea492'
CMake Warning at F:/GitHub/Multy-Core/multy_core/version_from_git.cmake:36 (message):
  Failed to obtain version information from git, using dummy values.

> [2/3] Building CXX object CMakeFiles/multy_core_jni.dir/F_/GitHub/Multy-Android/app/src/main/cpp/scratch.cpp.o
FAILED: C:\Users\Microsoft\AppData\Local\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=i686-none-linux-android21 --gcc-toolchain=C:/Users/Microsoft/AppData/Local/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/windows-x86_64 --sysroot=C:/Users/Microsoft/AppData/Local/Android/sdk/ndk-bundle/sysroot  -DHAVE_CONFIG_H -DMULTY_BUILD_FOR_ANDROID=1 -DMULTY_WITH_EOS=1 -DMULTY_WITH_GOLOS=1 -Dmulty_core_jni_EXPORTS -IF:/GitHub/Multy-Core/. -IF:/GitHub/Multy-Core/third-party/libwally-core/. -IF:/GitHub/Multy-Core/third-party/libwally-core/src -IF:/GitHub/Multy-Core/third-party/libwally-core/src/ccan -IF:/GitHub/Multy-Core/third-party/libwally-core/src/secp256k1 -IF:/GitHub/Multy-Core/third-party/libwally-core/src/secp256k1/include -IF:/GitHub/Multy-Core/third-party/libwally-core/src/secp256k1/src -IF:/GitHub/Multy-Core/third-party/. -IF:/GitHub/Multy-Core/third-party/jsoncpp/src/lib_json/../../include -isystem C:/Users/Microsoft/AppData/Local/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem C:/Users/Microsoft/AppData/Local/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem C:/Users/Microsoft/AppData/Local/Android/sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++11 -O0 -fno-limit-debug-info  -fPIC   -std=gnu++11 -MD -MT CMakeFiles/multy_core_jni.dir/F_/GitHub/Multy-Android/app/src/main/cpp/scratch.cpp.o -MF CMakeFiles\multy_core_jni.dir\F_\GitHub\Multy-Android\app\src\main\cpp\scratch.cpp.o.d -o CMakeFiles/multy_core_jni.dir/F_/GitHub/Multy-Android/app/src/main/cpp/scratch.cpp.o -c F:\GitHub\Multy-Android\app\src\main\cpp\scratch.cpp
F:\GitHub\Multy-Android\app\src\main\cpp\scratch.cpp:326:26: error: use of undeclared identifier 'account_change_private_key'
            HANDLE_ERROR(account_change_private_key(account.get(), -1, b));
                         ^
1 error generated.
ninja: build stopped: subcommand failed.

**Comment by Enmk** [comment]
Hi! It looks like version of multy_core you are using is outdated. Please try against [release-0.6.0](https://github.com/Multy-io/Multy-Core/commit/dbaf95a6ae42421b596c1a4e56cc7f21dd0911e9) this one has `account_change_private_key` for sure.
